kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    namespace: default
    name: namespace-reader
rules:
    - apiGroups: [""]
      resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
      verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: namespace-reader-binding
    namespace: default
subjects:
    - kind: ServiceAccount
      name: default
      apiGroup: ""
roleRef:
    kind: Role
    name: namespace-reader
    apiGroup: ""

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: spring-cloud-k8s-demo
data:
    application.properties: |-
        messageProp=k8s config map

---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: spring-cloud-k8s-demo-dep
    name: spring-cloud-k8s-demo-dep
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: spring-cloud-k8s-demo-dep
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: spring-cloud-k8s-demo-dep
        spec:
            containers:
                - image: spring-cloud-k8s-demo:latest
                  imagePullPolicy: Never
                  name: spring-cloud-k8s-demo
                  ports:
                      - containerPort: 8080
                        protocol: TCP
                  resources: {}

